apiVersion: v1
kind: Service
metadata:
  name: hct-frontend-svc
  namespace: hct-frontend-vilcapuma-marilyn
  labels:
    app: hct-frontend
spec:
  type: NodePort
  selector:
    app: hct-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
