events {
    worker_connections 1024;
}

http {
    server {
        listen 8097;

        location / {
            proxy_pass http://app:9096;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
