apiVersion: v1
kind: Service
metadata:
  name: hct-alquiler-svc
  namespace: hct-alquiler-vilcapuma-marilyn
  labels:
    app: hct-alquiler
spec:
  type: NodePort
  selector:
    app: hct-alquiler
  ports:
    - name: http
      port: 9092
      targetPort: 9092
      nodePort: 30092
