spring:
  application:
    name: marilynvilcapuma

  r2dbc:
#    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: ${SECRET_USERNAME:sa}
#    password: ${SECRET_PASSWORD:password}
    url: r2dbc:postgresql://ep-noisy-rain-anq1bkk7-pooler.c-6.us-east-1.aws.neon.tech/proyect?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_tWwEiO36fqGM

  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${APP_PORT:9095}

