apiVersion: v1
kind: Service
metadata:
  name: hct-cliente-svc
  namespace: hct-cliente-vilcapuma-marilyn
  labels:
    app: hct-cliente
spec:
  type: NodePort
  selector:
    app: hct-cliente
  ports:
    - name: http
      port: 9091
      targetPort: 9091
      nodePort: 30091
